-- Q_4-2 / DISTINCT를 이용한 중복없는 데이터 출력
SELECT DISTINCT JOB
  FROM EMP;

-- Q_4-3 / AS를 활용한 별칭지정 및 ORDER BY절을 활용한 정렬된 데이터 출력
SELECT EMPNO AS EMPLOYEE_NO, ENAME AS EMPLOYEE_NAME, JOB, MGR AS MANAGER, HIREDATE, SAL AS SALARY, COMM AS COMMISSION, DEPTNO AS DEPARTMENT_NO
  FROM EMP
 ORDER BY DEPTNO DESC, ENAME ASC;