-- Q_5-1 / LIKE 연산자 활용
SELECT *
  FROM EMP
 WHERE ENAME LIKE '%S';
 
-- Q_5-2 / AND 논리연산자 활용
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
  FROM EMP
 WHERE DEPTNO = 30
   AND JOB = 'SALESMAN';
   
-- Q_5-3(집합 연산자 사용x)
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
  FROM EMP
 WHERE DEPTNO IN (20, 30)
   AND SAL > 2000;

-- Q_5-3(집합 연산자 사용) / 정렬이 필요하다면 ORDER BY절 활용
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
  FROM EMP
 WHERE DEPTNO = 20
   AND SAL > 2000
UNION
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
  FROM EMP
 WHERE DEPTNO = 30
   AND SAL > 2000;
   
-- Q_5-4 / BETWEEN 연산자와 대소비교 연산자 비교
SELECT *
  FROM EMP
MINUS
SELECT *
  FROM EMP
 WHERE SAL >= 2000
   AND SAL <= 3000;
   
-- Q_5-5 / 다양한 연산자의 활용
SELECT ENAME, EMPNO, SAL, DEPTNO
  FROM EMP
 WHERE ENAME LIKE '%E%'
   AND DEPTNO = 30
   AND SAL NOT BETWEEN 1000 AND 2000;
   
-- Q_5-6 / IS NULL과 IN, LIKE 연산자 활용
SELECT *
  FROM EMP
 WHERE COMM IS NULL
   AND MGR IS NOT NULL
   AND JOB IN ('MANAGER', 'CLERK')
   AND ENAME NOT LIKE '_L%';