-- Q_6-1 / LENGTH,SUBSTR함수와 패딩처리 응용,
SELECT EMPNO, 
       RPAD(SUBSTR(EMPNO, 1, 2), 4, '*') AS MASKING_EMPNO, 
       ENAME, 
       RPAD(SUBSTR(ENAME, 1, 1), 5, '*') AS MASKING_ENAME
  FROM EMP
 WHERE LENGTH(ENAME) >= 5
   AND LENGTH(ENAME) < 6;

-- Q_6-2 / 숫자함수의 활용
SELECT EMPNO, 
       ENAME, 
       SAL, 
       TRUNC(SAL/21.5, 2) AS DAY_PAY, 
       ROUND(TRUNC(SAL/21.5, 2)/8, 1) AS TIME_PAY
  FROM EMP;
  
-- Q_6-3
SELECT EMPNO,
       ENAME,
       HIREDATE,
       TO_CHAR(NEXT_DAY(ADD_MONTHS(HIREDATE, 3), '월요일'), 'YYYY-MM-DD') AS R_JOB,
  CASE
   WHEN COMM IS NULL THEN 'N/A'
   ELSE TO_CHAR(COMM)
    END AS COMM
  FROM EMP;
-- NVL(TO_CHAR(COMM), 'N/A') AS COMM (CASE문을 NVL함수로 대체 가능)

-- Q_6-4
SELECT EMPNO, ENAME, MGR,
  CASE
   WHEN MGR IS NULL THEN '0000'
   WHEN TRUNC(MGR, -2) = 7500 THEN '5555'
   WHEN TRUNC(MGR, -2) = 7600 THEN '6666'
   WHEN TRUNC(MGR, -2) = 7700 THEN '7777'
   WHEN TRUNC(MGR, -2) = 7800 THEN '8888'
   ELSE TO_CHAR(MGR)
  END AS CHG_MGR
  FROM EMP;
-- MGR이 NUMBER타입이라 TRUNC함수가 보다 효율적이라 판단
-- SUBSTR(MGR, 1, 2)로 앞 두 자리만 비교하여 출력 가능